In [2]:
import torch
from torch import nn


而延迟写法只告诉它输出维度：
nn.LazyLinear(8)
# 输入特征数暂时不知道，输出8个特征

In [3]:
net = nn.Sequential(nn.LazyLinear(8), nn.ReLU(), nn.LazyLinear(1))
X = torch.rand(size=(2, 4))
net(X).shape

torch.Size([2, 1])

In [4]:
def init_normal(module):
    if type(module) == nn.Linear:
        nn.init.normal_(module.weight, mean=0, std=0.01)
        nn.init.zeros_(module.bias)

net.apply(init_normal)
print(net)
print(net[0].weight)
net[0].weight.data[0], net[0].bias.data[0]

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)
Parameter containing:
tensor([[ 0.0126, -0.0271,  0.0068,  0.0204],
        [-0.0050, -0.0025,  0.0114,  0.0102],
        [-0.0051,  0.0017,  0.0018, -0.0081],
        [-0.0025, -0.0134, -0.0116,  0.0249],
        [ 0.0015, -0.0049, -0.0293, -0.0165],
        [-0.0183,  0.0004, -0.0055, -0.0090],
        [ 0.0063,  0.0015, -0.0115,  0.0059],
        [ 0.0090, -0.0075,  0.0238, -0.0180]], requires_grad=True)


(tensor([ 0.0126, -0.0271,  0.0068,  0.0204]), tensor(0.))

In [5]:
def init_constant(module):
    if type(module) == nn.Linear:
        nn.init.constant_(module.weight, 1)
        nn.init.zeros_(module.bias)

net.apply(init_constant)
net[0].weight.data[0], net[0].bias.data[0]

(tensor([1., 1., 1., 1.]), tensor(0.))

In [8]:
def init_xavier(module):
    if type(module) == nn.Linear:
        nn.init.xavier_uniform_(module.weight)

def init_42(module):
    if type(module) == nn.Linear:
        nn.init.constant_(module.weight, 42)

net[0].apply(init_xavier)
print(net[0].weight)
net[2].apply(init_42)
print(net[2].weight)
print(net[0].weight.data[0])
print(net[2].weight.data)

Parameter containing:
tensor([[-0.0690,  0.3400,  0.1493,  0.5013],
        [-0.6721,  0.1410,  0.1995, -0.0222],
        [-0.3040, -0.5694, -0.4187, -0.3794],
        [-0.6720,  0.1886, -0.4467, -0.6273],
        [-0.2272, -0.1761,  0.5029,  0.1881],
        [-0.1452,  0.3329, -0.6592, -0.3184],
        [ 0.1232,  0.5622,  0.4677, -0.2240],
        [-0.0305, -0.4826,  0.1434, -0.4059]], requires_grad=True)
Parameter containing:
tensor([[42., 42., 42., 42., 42., 42., 42., 42.]], requires_grad=True)
tensor([-0.0690,  0.3400,  0.1493,  0.5013])
tensor([[42., 42., 42., 42., 42., 42., 42., 42.]])


In [9]:
def my_init(module):
    if type(module) == nn.Linear:
        print("Init", *[(name, param.shape)
                        for name, param in module.named_parameters()][0])
        nn.init.uniform_(module.weight, -10, 10)
        module.weight.data *= module.weight.data.abs() >= 5

net.apply(my_init)
net[0].weight[:2]

Init weight torch.Size([8, 4])
Init weight torch.Size([1, 8])


tensor([[-8.1029,  0.0000, -0.0000,  7.4856],
        [ 5.4742, -7.6859, -0.0000,  8.1761]], grad_fn=<SliceBackward0>)

In [14]:
print(net[0].weight.data)
net[0].weight.data[:] += 1
net[0].weight.data[0, 0] = 30
print(net[0].weight.data)
net[0].weight.data[0]

tensor([[30.0000,  4.0000,  4.0000, 11.4856],
        [ 9.4742, -3.6859,  4.0000, 12.1761],
        [ 4.0000,  4.0000, -2.8841, -1.6635],
        [ 4.0000,  4.0000,  4.0000, 10.5163],
        [-2.3536,  4.0000, -4.6062,  4.0000],
        [ 4.0000,  4.0000,  4.0000, -4.4472],
        [ 4.0000, 11.0134,  4.0000,  4.0000],
        [13.1731, 12.5162,  9.0506,  4.0000]])
tensor([[30.0000,  5.0000,  5.0000, 12.4856],
        [10.4742, -2.6859,  5.0000, 13.1761],
        [ 5.0000,  5.0000, -1.8841, -0.6635],
        [ 5.0000,  5.0000,  5.0000, 11.5163],
        [-1.3536,  5.0000, -3.6062,  5.0000],
        [ 5.0000,  5.0000,  5.0000, -3.4472],
        [ 5.0000, 12.0134,  5.0000,  5.0000],
        [14.1731, 13.5162, 10.0506,  5.0000]])


tensor([30.0000,  5.0000,  5.0000, 12.4856])