In [1]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

现在，我们可以将层作为组件合并到更复杂的模型中。

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-7.5670e-09, grad_fn=<MeanBackward0>)

In [23]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        print(self.bias.data)
        return F.relu(linear)

In [24]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.4279, -1.0008, -2.7124],
        [ 0.8096,  0.1612,  0.7154],
        [ 0.0942,  0.9789,  1.0745],
        [-0.4389,  2.3109,  0.0937],
        [ 0.2217,  1.1072,  0.8558]], requires_grad=True)

In [25]:
print(linear(torch.rand(2, 5)))

tensor([ 0.1957,  0.1864, -0.3750])
tensor([[0.8110, 1.6034, 0.0000],
        [0.5210, 2.4379, 0.7897]])


In [16]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([ 0.8620, -2.0044, -1.3707,  0.2536,  1.6453,  0.3417,  0.1474,  0.3968])
tensor([-1.5753])


tensor([[0.],
        [0.]])