In [ ]:
import torch, numpy as np
from torch.distributions import multinomial
import matplotlib.pyplot as plt

SyntaxError: invalid syntax (1771595448.py, line 2)

In [3]:
fair_probs = torch.ones([6]) / 6
multinomial.Multinomial(1, fair_probs).sample()

tensor([0., 0., 0., 0., 0., 1.])

In [4]:
multinomial.Multinomial(10, fair_probs).sample()

tensor([5., 1., 1., 0., 2., 1.])

In [5]:
# 将结果存储为32位浮点数以进行除法
counts = multinomial.Multinomial(1000, fair_probs).sample()
counts / 1000  # 相对频率作为估计值

tensor([0.1890, 0.1530, 0.1720, 0.1440, 0.1770, 0.1650])