In [ ]:
import numpy as np
a=np.random.rand(5)
print(a)#这里的a是一个长度为5的一维数组，里面的元素是随机生成的浮点数，范围在0到1之间。
print(a.shape)#这里的shape属性返回了a的形状，即(5,)，表示a是一个长度为5的一维数组。
print(a.T)#这里的T属性返回了a的转置，但是由于a是一维数组，所以转置后还是一个长度为5的一维数组。
#它既不是行向量也不是列向量，而是一个一维数组。它没有明确的行数和列数，只有一个维度。
#如果你想把它变成一个行向量，可以使用reshape方法：
print(np.dot(a,a.T))#这里的dot函数计算了a和a的转置的点积，结果是一个标量。
a = a.reshape(5, 1)
print(a)#这里的a现在是一个5x1的二维数组，也就是一个列向量。
print(np.dot(a,a.T))#这里的dot函数计算了a和a的转置的点积，结果是一个5x5的矩阵。

[0.37103452 0.45140442 0.8581776  0.60300756 0.65226539]
(5,)
[0.37103452 0.45140442 0.8581776  0.60300756 0.65226539]
1.8669696224904444
[[0.37103452]
 [0.45140442]
 [0.8581776 ]
 [0.60300756]
 [0.65226539]]
[[0.13766662 0.16748662 0.31841351 0.22373662 0.24201298]
 [0.16748662 0.20376595 0.38738517 0.27220028 0.29443548]
 [0.31841351 0.38738517 0.73646879 0.51748758 0.55975955]
 [0.22373662 0.27220028 0.51748758 0.36361812 0.39332096]
 [0.24201298 0.29443548 0.55975955 0.39332096 0.42545014]]


In [ ]:
b=np.random.randn(5,1)
print(b)#这里生成的就是一个列向量
print(b.T)

[[ 1.53952433]
 [ 0.83797036]
 [-0.8881629 ]
 [-2.27587774]
 [ 0.38338437]]
[[ 1.53952433  0.83797036 -0.8881629  -2.27587774  0.38338437]]
