Miscellaneous

In [2]:
import numpy as np

In [5]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata=filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


Booleam Masking and Advanced Indexing

In [6]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [ ]:
# can idex the array with a boolean array or 
# a conditional statement like above to return the values that satisfy the condition
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [8]:
# can index with a list
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[[1,3,5]])

[2 4 6]


In [11]:
print(np.any(filedata>50,axis=0))# check if any values in the array are greater than 50
print(np.all(filedata>50,axis=0))# check if all values in the array are greater than 50
print(np.any(filedata>50,axis=1))# check if any values in each row are greater than 50
print(np.all(filedata>50,axis=1))# check if all values in each row are greater than 50

[False False False False  True  True False  True  True False False False
 False False False False  True  True]
[False False False False  True False False False False False False False
 False False False False False False]
[ True  True  True]
[False False False]


In [12]:
((filedata>50) & (filedata<100))# check if values are between 50 and 100

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [13]:
(~((filedata>50) & (filedata<100)))# check if values are not between 50 and 100

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [15]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [16]:
b[[0,1,2,3,4],[0,1,2,3,4]]# get the diagonal values of the array

array([ 1,  7, 13, 19, 25])

In [ ]:
vals = [4,5,19,20,24,25]
mask = np.isin(b, vals)
print(b[mask]) # get values from b that are in vals list

[ 4  5 19 20 24 25]
