Reorganizing Arrays

In [3]:
import numpy as np

In [4]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after1=before.reshape(8,1)
print(after1)
after2=before.reshape(2,2,2)
print(after2)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
v1=np.array([1,2,3,4,5])
v2=np.array([6,7,8,9,10])
print(np.vstack([v1,v2]))# stack the two vectors vertically
print(np.hstack([v1,v2]))# stack the two vectors horizontally
print(np.vstack([v1,v2]).T)# transpose the vertically stacked vectors
print(np.vstack([v1,v1,v2]))# stack the three vectors vertically
print(np.hstack([v1,v1,v2]))# stack the three vectors horizontally

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[[ 1  2  3  4  5]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  1  2  3  4  5  6  7  8  9 10]
