Linear Algerbra

In [1]:
import numpy as np

In [3]:
a=np.ones((2,3))
b=np.full((3,2),2)
print(a)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
# find the determinant of a matrix
c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [6]:
#find the trace of a matrix
d=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.trace(d)

np.int64(15)

In [7]:
# find the eigenvalues and eigenvectors of a matrix
e=np.array([[1,2],[3,4]])
np.linalg.eig(e)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [8]:
# find the inverse of a matrix
f=np.array([[1,2],[3,4]])
np.linalg.inv(f)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
# singular value decomposition,
# which is a factorization of a matrix into three matrices,
#  U, S, and V, where U and V are orthogonal matrices 
# and S is a diagonal matrix containing the singular values of the original matrix.
g=np.array([[1,2],[3,4]])
np.linalg.svd(g)

SVDResult(U=array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), S=array([5.4649857 , 0.36596619]), Vh=array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))

In [10]:
# find the norm of a vector
h=np.array([1,2,3])
np.linalg.norm(h)

np.float64(3.7416573867739413)