Load in Numpy

In [2]:
import numpy as np

The Basics

In [ ]:
a=np.array([1,2,3,4,5])# 1D array
print(a)

[1 2 3 4 5]


In [ ]:
b=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]]) # 2D array
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


The dimension

In [5]:
print(a.ndim)
print(b.ndim)

1
2


The Shape

In [6]:
print(a.shape)
print(b.shape) #rows and columns,rows first and then columns

(5,)
(2, 3)


The Type

In [7]:
print(a.dtype)
print(b.dtype)

int64
float64


In [ ]:
c=np.array([1,2,3],dtype='int16') #specifying the data type
print(c)
print(c.dtype)

[1 2 3]
