Statistics

In [1]:
import numpy as np

In [20]:
stats = np.array([[10, 200, 300], [5, 2, 250], [1, 150, 3], [100, 120, 130]])
print(stats)

[[ 10 200 300]
 [  5   2 250]
 [  1 150   3]
 [100 120 130]]


In [ ]:
print(np.min(stats))
print(np.min(stats, axis=0))# find the minimum value in each column
print(np.min(stats, axis=1))# find the minimum value in each row
print(np.max(stats))
print(np.mean(stats))
print(np.median(stats))
print(np.std(stats))
print(np.sum(stats))

1
[1 2 3]
[ 10   2   1 100]
300
105.91666666666667
110.0
100.75503158100288
