Initialize

In [ ]:
import numpy as np
np.zeros((2,3,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [2]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [8]:
a=np.full((2,2,2),fill_value=5,dtype=np.int16)
print(a)

[[[5 5]
  [5 5]]

 [[5 5]
  [5 5]]]


In [10]:
np.full_like(a,fill_value=3) 
# #creates an array with the same shape and type as a, filled with 5

array([[[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]]], dtype=int16)

In [15]:
print(np.random.rand(2,3)) 
#creates an array of the given shape and populates it with random samples from a uniform distribution over [0, 1)
print(np.random.randint(1,10,size=(3,4)))
#creates an array of the given shape and populates it with random integers from low (inclusive) to high (exclusive)
print(np.random.choice([1,2,3,4,5],size=(3,4)))
#creates an array of the given shape and populates it with random samples from a given

[[0.05607858 0.0355307  0.92786682]
 [0.76341543 0.80668809 0.56432892]]
[[7 3 9 6]
 [9 5 7 4]
 [4 3 3 7]]
[[2 3 5 2]
 [4 2 5 2]
 [5 2 3 4]]


In [17]:
np.random.random_sample(a.shape)
#creates an array of the given shape and populates it with random samples from a uniform distribution

array([[[0.53898149, 0.04724063],
        [0.6496936 , 0.00156009]],

       [[0.72498371, 0.60870693],
        [0.41834832, 0.58924234]]])

In [ ]:
np.identity(5)
#creates a 2-D array with ones on the diagonal and zeros elsewhere

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
r1=np.reshape(arr,(9,))
# np.reshape() function is used to give a new shape to an array without changing its data. 
# It returns a new array with the specified shape.
print(r1)
r2=np.reshape(arr,(1,9))
print(r2)


[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]]


In [ ]:
r3=np.repeat(arr,3,axis=0)
# np.repeat() function is used to repeat elements of an array.
#  The axis parameter specifies the axis along which to repeat values.
print(r3)
r4=np.repeat(arr,3,axis=1)
print(r4)
r5=np.repeat(arr,3,axis=None)
# If axis is None, the input array is flattened before repetition.
print(r5)
r6=np.repeat(arr,3,axis=2)
# If axis is greater than or equal to the number of dimensions of the input array, a ValueError is raised.
print(r6)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]
 [7 8 9]]
[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]
 [7 7 7 8 8 8 9 9 9]]
[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6 7 7 7 8 8 8 9 9 9]


AxisError: axis 2 is out of bounds for array of dimension 2