Acessing/Changing specific elements,rows,columns,etc

In [4]:
import numpy as np
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])  # 2D array with 2 rows and 7 columns
print(a)
print(a.shape) #rows and columns,rows first and then columns
print(a.ndim) #number of dimensions
print(a.dtype) #data type of the elements in the array

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)
2
int64


In [6]:
a[1,5],a[1][5],a[1,-2] #accessing specific elements in the array

(np.int64(13), np.int64(13), np.int64(13))

In [15]:
print(a[0,:]) #accessing all the elements in the first row
print(a[:,0]) #accessing all the elements in the first column

[1 2 3 4 5 6 7]
[1 8]


In [14]:
print(a[0,1:6:2]) #accessing specific elements in the first row
# start index is 1(inclusive), end index is 6(exclusive) and step is 2
print(a[0,1:-2:2])

[2 4 6]
[2 4]


In [17]:
a[1,5]=20
print(a)
a[:,2]=10
print(a)
a[:,2]=[10,20]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2 10  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2 10  4  5  6  7]
 [ 8  9 20 11 12 20 14]]


In [ ]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 3D array with 2 blocks, 2 rows and 2 columns
print(b)
print(b[0,0,1]) #accessing specific element in the 3D array
print(b[0,1,:]) #accessing specific elements in the 3D array
print(b[:,1,:]) #accessing specific elements in the 3D array

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
2
[3 4]
