polunomial

In [7]:
import numpy as np
from numpy.polynomial import polynomial,chebyshev,legendre,hermite

In [8]:
p= polynomial.Polynomial([1,2,3])
print(p)

1.0 + 2.0 x + 3.0 x**2


In [9]:
p_root=polynomial.Polynomial.fromroots([-1,1]) #(x+1)(x-1)=x^2-1
print(p_root)

-1.0 + 0.0 x + 1.0 x**2


In [11]:
x=np.array([0,1,2,3,4])
y=np.array([1,3,5,7,9])
p_fit=polynomial.Polynomial.fit(x,y,deg=1)# fit a polynomial of degree 1 (line) to the data points
# polynomial.Polynomial.fit(x, y, deg=1) 用最小二乘拟合一个一次多项式（直线）到数据 (x,y)，返回一个 Polynomial 对象表示拟合结果。 
print(p_fit)
p_fit=polynomial.Polynomial.fit(x,y,deg=2)# fit a polynomial of degree 2 (quadratic) to the data points
print(p_fit)

5.0 + 4.0 (-1.0 + 0.5x)
5.0 + 4.0 (-1.0 + 0.5x) + (3.17402984e-15) (-1.0 + 0.5x)**2


np.linalg.lstsq —— 最小二乘法求解器

用途：求解线性方程组 Ax=b当方程数大于未知数时（超定）寻找最小平方误差解，或当矩阵奇异时给出最小范数解。

函数签名：
np.linalg.lstsq(a, b, rcond=None)

a: 系数矩阵 (M, N)

b: 因变量值 (M,) 或 (M, K)

rcond: 奇异值截断阈值，一般用默认或 rcond=None

返回：(x, residuals, rank, s)

x: 最小二乘解

residuals: 残差平方和（当 M>N 且矩阵满秩时）

rank: 矩阵 a 的秩

s: 奇异值

In [14]:
# 数据点
x = np.array([0, 1, 2, 3, 4])
y = np.array([1.1, 3.2, 4.9, 7.2, 9.3])
print(x)
print(y)
# 构造矩阵 A: [x, 1]  ->  y = kx + b
A = np.vstack([x, np.ones(len(x))]).T
print(A)
k, b = np.linalg.lstsq(A, y, rcond=None)[0]
print(f"斜率: {k:.3f}, 截距: {b:.3f}")   # 输出接近 2.05, 1.02

[0 1 2 3 4]
[1.1 3.2 4.9 7.2 9.3]
[[0. 1.]
 [1. 1.]
 [2. 1.]
 [3. 1.]
 [4. 1.]]
斜率: 2.040, 截距: 1.060


np.linalg.qr —— QR 分解

用途：将矩阵分解为 A=QR，其中 Q 是正交矩阵，R 是上三角矩阵。常用于求解最小二乘、特征值计算、稳定求逆等。

函数签名：
np.linalg.qr(a, mode='reduced')

mode: 'reduced'（默认）返回经济型分解，'complete' 返回完整方阵 Q

返回 (Q, R)

In [16]:
A = np.vstack([x, np.ones(len(x))]).T
print(A)
# QR 分解
Q, R = np.linalg.qr(A)
print(Q)
print(R)
# 求解 Rx = Qᵀy
y = np.array([1.1, 3.2, 4.9, 7.2, 9.3])
coef = np.linalg.solve(R, Q.T @ y)
print(coef)   # [2.05, 1.02] 与 lstsq 一致

[[0. 1.]
 [1. 1.]
 [2. 1.]
 [3. 1.]
 [4. 1.]]
[[ 0.00000000e+00 -7.74596669e-01]
 [-1.82574186e-01 -5.16397779e-01]
 [-3.65148372e-01 -2.58198890e-01]
 [-5.47722558e-01  1.27331956e-16]
 [-7.30296743e-01  2.58198890e-01]]
[[-5.47722558 -1.82574186]
 [ 0.         -1.29099445]]
[2.04 1.06]


np.linalg.svd —— 奇异值分解

用途：将矩阵分解为 A=USV^T U 和 V 是正交矩阵，S 是对角阵（奇异值）。SVD 是数值线性代数的基石，用于主成分分析（PCA）、伪逆、数据压缩、推荐系统等。

函数签名：
np.linalg.svd(a, full_matrices=True, compute_uv=True)

full_matrices: 是否返回完整尺寸的 U 和 Vh

compute_uv: 是否计算 U 和 Vh（若为 False 只返回奇异值）

返回：(U, S, Vh) （若 compute_uv=True）

In [21]:
#TODO

np.where

In [19]:
arr = np.array([1, -2, 3, -4, 5])
# 将负数替换为 0
result = np.where(arr < 0, 0, arr)   # [1, 0, 3, 0, 5]
print(result)
# 获取正数索引
idx = np.where(arr > 0)   # (array([0, 2, 4]),)
print(idx)

[1 0 3 0 5]
(array([0, 2, 4]),)


In [ ]:
scores = np.array([85, 62, 97, 43, 71])
conditions = [
    scores >= 90, # this will return a boolean array: =[False, False, True, False, False]
    scores >= 80, # [True, False, True, False, False] (but the first condition already captures the 97)
    scores >= 70,
    scores >= 60
]
choices = ['A', 'B', 'C', 'D']
grades = np.select(conditions, choices, default='F')
print(grades)   # ['B' 'D' 'A' 'F' 'C']

['B' 'D' 'A' 'F' 'C']


In [23]:
x = np.array([1e-10, 1, 10])
np.log1p(x)   # 比 np.log(1+x) 在小值时更精确

array([1.00000000e-10, 6.93147181e-01, 2.39789527e+00])